version: "3"
services:
  microwatcher:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/usr/local/bin/micropython", "/app/main.py"]
    volumes:
      - .:/app
    stdin_open: true
    tty: true
